### ISSUE TITLE
Docs Suggestions

### ISSUE THREAD

**Issue by 1cg** [jfbrennan/m-#27]
Editorial opinion, worth exactly what you paid for it:

I appreciate and agree with a lot of what you have to say about modern web development (especially the J2EE comparison) but I wonder if some people might find it alienating.  I used to be more aggressive with my messaging around htmx/intercooler.js, but I dialed it back over time and have had more success, fwiw.

For the docs site, I'm not sure how you are hosting it, but I am using netlify for htmx and it has worked really well.  I am using the eleventy static site building system, which is OK, but is supported by netlify OOTB (including layouts, etc.)  You get https almost for free, which is also nice.

Finally, my first impression of m- is concern about the custom tags.  I know that custom tags are a thing, but I just don't have a lot of experience with them.  I see them briefly mentioned (https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements) but for someone like me, a bit more information on them would help me get comfortable with them.

Good luck w/ the project!

**Comment by jfbrennan** [comment]
Thanks, really do appreciate it. I hear you about dialing it back, mind sharing some of parts you think should change? Happy to take that and work with it.

I just use Elastic Beanstalk, super easy. Haven't bothered to buy a cert yet, but plan on it for sure (if nothing else, it just doesn't look professional with that "Not secure" message).

I do have a link to an article about custom HTML tags, but I think you're right. A little more technical explanation would help remove some doubts/concerns/questions. FWIW I've used them for a few years now and found zero issues. Browsers were designed to support them, they initialize as [`HTMLUnknownElement `](https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement), which extends `HTMLElement`
