### ISSUE TITLE
Some info

### ISSUE THREAD

**Issue by camillo777** [jfbrennan/m-#29]
Hello,
I am trying to use this library for my project, I have 2 issues:

1) I cannot find in the docs the description of "bg-white" class, I understand it defines background color, but when I apply for example it to a span element it does not work; is there a way to do something like this: 

`<span class="bg-red">1</span>`

2) Is there a way to have a bigger "badge" (and maybe a square one?); doing something like this will cut the text:

`<m-badge count="2" class="txt-lg">`

while doing this will make it a rounded rectangle instead of a circle:

`<m-badge count="2" class="txt-lg mar-all-sm">`

Thank you!
Camillo

**Comment by jfbrennan** [comment]
Thanks for the feedback!

-I'll double check the bg color docs.
-Square badge would be a custom style you'd have to decide if you wanted (could maybe add a `brd-radius-none` util class to make it easy...). And you're almost there for a rounded rectangle, try `<m-badge count="1" class="txt-xl pad-all-md"></m-badge>`, which renders:

<img width="769" alt="Screen Shot 2020-11-18 at 2 19 24 PM" src="https://user-images.githubusercontent.com/1817868/99604223-1563b580-29a9-11eb-86e5-5b901de03ab1.png">

**Comment by jfbrennan** [comment]
`<m-badge count="100" class="txt-lg pad-all-sm brd-radius-sm"></m-badge>` might actually be a little closer?

**Comment by jfbrennan** [comment]
@camillo777 I think the above will work well. If not, feel free to discuss.
