### ISSUE TITLE
Icons doc page is broken

### ISSUE THREAD

**Issue by mppfiles** [jfbrennan/m-#31]
The icons showcase is not working. The page shows this error:

````
Uncaught DOMException: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet
````

**Comment by jfbrennan** [comment]
Thanks for reporting!

Fix is done, will be pushing next week (on vaca)

**Comment by jcschmidig** [comment]
I found an archived version!
https://web.archive.org/web/20201130135659/https://m-docs.org/icons#all-icons

**Comment by jfbrennan** [comment]
Fix has been published
