### ISSUE TITLE
m-docs.org is broken

### ISSUE THREAD

**Issue by jcschmidig** [jfbrennan/m-#32]
Documentation missing!

**Comment by jcschmidig** [comment]
use http://m-docs.org (without ssl)

**Comment by jfbrennan** [comment]
@jcschmidig Did you find a `https` link somewhere? I haven't set up ssl yet, so I want to make sure there aren't any links out there sending people to that

**Comment by jcschmidig** [comment]
Yes. Here is the source out of the npm page:
<p>Try M- right now by just linking to the CDN files below and then visit the <a href="https://m-docs.org" rel="nofollow">doc site</a> to learn more. If you want to use your own design language, just fork this project and customize the code (it's a really easy codebase to work in).</p>

**Comment by jcschmidig** [comment]
BTW, why don't you use Let's Encrypt?

**Comment by jfbrennan** [comment]
Fixed the link, thanks for reporting.

I just haven't got around to setting up https, def need to get that done though. LE is free, right?

**Comment by jcschmidig** [comment]
Yes, LE is free!

**Comment by jfbrennan** [comment]
HTTPS is live https://m-docs.org
