### ISSUE TITLE
https://unpkg.com/m-@1.2.4/dist/dev.css not found

### ISSUE THREAD

**Issue by cilex-ft** [jfbrennan/m-#44]
Home doc page says:

### CDN
Development: https://unpkg.com/m-@1.2.4/dist/dev.[css|js]

But these files are [not found on unpkg](https://unpkg.com/m-@1.2.4/dist/dev.css)

    Cannot find "/dist/dev.css" in m-@1.2.4

**Comment by jfbrennan** [comment]
Thanks for reporting. Will take a look

**Comment by jfbrennan** [comment]
Removing broken link in docs, will add source maps support soon.
