### ISSUE TITLE
Question: How should I override the values of the tokens inside custom-props.css ?

### ISSUE THREAD

**Issue by omawhite** [jfbrennan/m-#45]
This seems like a really cool lite weight library and I love how its framework agnostic and seems like a good option for building a design system on top of. I'm wondering if there is a recommended way to change the value of some of the tokens so I can try to "theme" m-dash to my liking? 

I'm new to css variables so if there's an obvious solution it eludes me. I thought that perhaps you could just create your own css file in your project and assign new values to the tokens you defined, but again not sure if that's the way to go. Any thoughts?

**Comment by jfbrennan** [comment]
Thanks Oma! I forked and themed it with our design language at OctoML. You can try that
