### ISSUE TITLE
[Question] Does m- work well with tailwind css for e.g.?

### ISSUE THREAD

**Issue by simkimsia** [jfbrennan/m-#73]
I'm more of a backend but i am intrigued by the promise m- can work with any technology.

Can m- work with tailwind as well?

**Comment by jfbrennan** [comment]
Technically yes, but you shouldn't. Their styles are likely to collide.

Mdash includes 180+ utility classes (similar to Tailwind in this regard) in addition to its 20+ components (Tailwind does not have components, only suggested patterns). It's intended that you'd use Mdash for core UI elements and styles + whatever JS application framework you like (Vue, Svelte, Riot, etc.).

If you'd like more utility classes in Mdash, I'm happy to add them (or accept pull requests) 👍
