### ISSUE TITLE
Broken example on Autocomple demo page in Firefox.

### ISSUE THREAD

**Issue by TomasLoow** [jfbrennan/m-#74]
On the page https://m-docs.org/autocomplete this happens when I try out the State Autocomple example under the *More Autocomplete!* header.

![image](https://user-images.githubusercontent.com/12694374/161372521-c1f446c6-a1fc-4554-a83d-3634a99ddac3.png)

This is on with Firefox v99, Windows 10.

I don't know enough CSS to figure out why it happens though. Maybe some bad z-index values?

**Comment by jfbrennan** [comment]
I *think* I have fixed this in my company's fork, will try to repro and fix. Thanks for reporting!

**Comment by jfbrennan** [comment]
Forgot to close (is fixed)
