### ISSUE TITLE
The connectedCallback runs multiple times

### ISSUE THREAD

**Issue by Danny-Engelman** [jfbrennan/m-#75]
Like the subject says, when you move/drag drop elements in the DOM, the ``connectedCallback`` will run again.

**Comment by jfbrennan** [comment]
I'd need more info @Danny-Engelman. Is this in regards to a specific component or all of the Custom Element components?

**Comment by Danny-Engelman** [comment]
The ``connectedCallback`` runs for every (re)placement in the DOM

https://jsfiddle.net/WebComponents/mc1o94kw/

```
<script>
  customElements.define('my-element', class extends HTMLElement {
    connectedCallback() {
      this.innerHTML += "<h1>Click me!</h1>";
      this.onclick = (evt) => document.body.append(this);
    }
  });
</script>

<my-element></my-element>
```
