### ISSUE TITLE
Tailwind Comparision

### ISSUE THREAD

**Issue by virat2010** [jfbrennan/m-#80]
Could you please provide in the docs of the size of tailwind? I would love to see the comparison.
Here:
![image](https://user-images.githubusercontent.com/59180983/202537013-fba1876b-fec9-4f5f-807d-97449810bd00.png)

**Comment by virat2010** [comment]
Tailwind compressed is about 46.2kb although depending on how you see it  you can say it's really 190.2kb but it all really depends on your project. Unless you set it up it will always be uncontrollably big (Learnt it the hard way.)

**Comment by jfbrennan** [comment]
@virat2010 looks like you answered your own question. Hopefully most folks realize they need to custom build TW and not include the whole monster!
