### ISSUE TITLE
Docs site SSL certificate expired

### ISSUE THREAD

**Issue by stephenbenedict** [jfbrennan/m-#93]
SSL certificate for https://m-docs.org/ appears to have expired.

**Comment by jfbrennan** [comment]
Thanks for reporting. Currently looking at cheaper alternatives to AWS where I manage everything.

**Comment by stephenbenedict** [comment]
Would recommend NearlyFreeSpeech.net if you haven't already.

**Comment by tarpagad** [comment]
![image](https://github.com/jfbrennan/m-/assets/32228204/89e615ad-92ce-459b-a8c9-ea47554be935)
There are a thousands of free good options these days

**Comment by jfbrennan** [comment]
Fixed. Not sure how much longer I want to pay the AWS bill, may find free alternatives some time.
