### ISSUE TITLE
Button focus styles

### ISSUE THREAD

**Issue by kodeFant** [jfbrennan/m-#95]
Hi! I really love the project! I feel it's the closest I have seen to a UI system I would like.

I found one obvious accessibility issue with buttons. When navigating with tab on the keyboard, there is not way of knowing if a button is focused or not because the outline seems to be completely removed.

Could we add some focus styles to buttons?

**Comment by jfbrennan** [comment]
Thanks and yes to focus for buttons! I have a batch of little improvements offline, I'll see if I have that already. If not, I'll actually update this issue to encompass focus styles across the system (I've been meaning to give inputs a stronger focus style)

**Comment by kodeFant** [comment]
Thanks! Much appreciated!
